export const DATA_REQUEST = 'DATA_REQUEST';
export const DATA_SUCCESS = 'DATA_SUCCESS';
export const DATA_FAILURE = 'DATA_FAILURE';
export const SELECT_DATA_REQUEST = 'SELECT_DATA_REQUEST';
export const SELECT_DATA_SUCCESS = 'SELECT_DATA_SUCCESS';
export const SELECT_DATA_FAILURE = 'SELECT_DATA_FAILURE';